"use client";
import { useState, useEffect, useRef } from "react";
import dynamic from "next/dynamic";
import { ArrowUpRight, ArrowRight, ChevronLeft, ChevronRight, RotateCcw, Maximize, Minimize, Layers3, Play, Pause, Wheat, Cpu, X, Move, ZoomIn, ZoomOut, Sparkles, Info } from "lucide-react";
import { Switch } from "@/components/ui/switch";
import { stages } from "./data/stages";
const Factory = dynamic(() => import("./components/factory"), { ssr: false, loading: () => <div className="loading-scene"><span className="loading-ring"/><p>Preparing your view of the future…</p></div> });
export default function Home() {
 const [ai,setAI]=useState(true),[selected,setSelected]=useState<number|null>(null),[cutaway,setCutaway]=useState(false),[playing,setPlaying]=useState(true),[reset,setReset]=useState(0),[zoom,setZoom]=useState(0),[layer,setLayer]=useState(false),[phase,setPhase]=useState(2),[full,setFull]=useState(false),[info,setInfo]=useState(false);
 const root=useRef<HTMLElement>(null),stage=selected===null?null:stages[selected];
 useEffect(()=>{const sync=()=>setFull(!!document.fullscreenElement);document.addEventListener("fullscreenchange",sync);return()=>document.removeEventListener("fullscreenchange",sync);},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setSelected(null);setLayer(false);setInfo(false);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
 function choose(i:number){setSelected(i);setLayer(false);}
 function resetView(){setSelected(null);setLayer(false);setReset(n=>n+1);}
 function changePhase(n:number){setPhase(n);setAI(n>0);setLayer(n===2);setSelected(null);}
 return <main className="experience" ref={root}>
 <header className="topbar"><a className="identity" href="#" onClick={e=>{e.preventDefault();resetView();}} aria-label="Return to facility overview"><span className="brand-icon"><Wheat size={23}/></span><span>MALT<span className="brand-slash"> / </span>FUTURES</span></a><div className="top-context">AN INDUSTRIAL AI EXPLORATION <span>2026</span></div><button className="concept-pill" onClick={()=>setInfo(!info)}><Info size={13}/> Concept experience</button></header>
 <section className="intro" aria-label="Introduction"><p className="eyebrow"><span/> FROM GRAIN TO INTELLIGENCE</p><h1>Inside the future<br/>of <em>malting.</em></h1><p className="intro-copy">A familiar industry.<br/>An entirely new perspective.</p></section>
 <div className="view-mode"><span className={!ai?"active-mode":""}>Traditional facility</span><Switch aria-label="AI-enabled facility" checked={ai} onCheckedChange={v=>{setAI(v);setPhase(v?2:0);if(!v)setLayer(false);}}/><span className={ai?"active-mode":""}><Sparkles size={14}/> AI-enabled facility</span></div>
 <section className="scene" aria-label="Interactive 3D malting facility. Drag to rotate, scroll or pinch to zoom."><Factory ai={ai} selected={selected} cutaway={cutaway} playing={playing} reset={reset} zoom={zoom} layer={layer} onSelect={choose}/></section>
 <aside className={"story-panel "+(stage||layer?"is-detail":"")} aria-live="polite">
 {layer&&ai?<><div className="panel-kicker"><Cpu size={16}/> THE AI CONTROL LAYER <button onClick={()=>setLayer(false)} aria-label="Close control layer"><X size={16}/></button></div><h2>One connected<br/><em>intelligence.</em></h2><p>Connect signals from the field, the factory and the market to support better operational decisions.</p><div className="signal-list">{[["Agriculture","Harvest signals & grain characteristics"],["Production","Equipment, process & quality data"],["Logistics","Inventory & dispatch availability"],["Customers","Demand & malt specifications"]].map(([a,b],i)=><div key={a}><span>0{i+1}</span><section><b>{a}</b><small>{b}</small></section></div>)}</div><p className="ai-note">Proposed actions remain subject to operator approval and process safeguards.</p></>:stage?<><div className="panel-kicker"><span>0{selected!+1} / THE MALTING JOURNEY</span><button onClick={()=>setSelected(null)} aria-label="Close stage details"><X size={16}/></button></div><h2>{stage.title}</h2><p>{stage.description}</p><div className={"insight "+(ai?"intelligent":"")}><div className="insight-label">{ai?<Cpu size={15}/>:<Layers3 size={15}/>} {ai?"WITH AI":"TRADITIONAL FACILITY"}</div><h3>{ai?stage.aiTitle:stage.tradTitle}</h3><p>{ai?stage.aiText:stage.tradText}</p></div><div className="detail-nav"><button aria-label="Previous stage" onClick={()=>choose((selected!+5)%6)}><ChevronLeft size={18}/></button><span>0{selected!+1}<small> / 06</small></span><button aria-label="Next stage" onClick={()=>choose((selected!+1)%6)}><ChevronRight size={18}/></button></div></>:<><div className="overview-rule"/><p className="overview-text">Explore how intelligence can connect every step of the journey — from the first grain to the finished malt.</p><button className="explore-btn" onClick={()=>choose(0)}>Explore the facility <ArrowUpRight size={20}/></button><span className="small-caption">Six stages. One connected value chain.</span><div className="mode-note"><span className={ai?"status-dot":"status-dot off"}/>{ai?"AI connections visible":"Conventional process view"}</div></>}
 </aside>
 {info&&<div className="info-popover" role="dialog" aria-label="About this concept"><button className="close-info" onClick={()=>setInfo(false)} aria-label="Close information"><X size={18}/></button><h3>A possible future, illustrated.</h3><p>A strategic concept inspired by Soufflet & Malt. This is not a real facility, an official company representation or an operational digital twin.</p><p>The layout, animated flows and AI applications are illustrative. No company performance data is presented.</p></div>}
 <div className="scene-tools"><button className={cutaway?"is-on":""} aria-pressed={cutaway} onClick={()=>setCutaway(!cutaway)} title="See inside the facility"><Layers3 size={17}/><span>Cutaway</span></button><button onClick={resetView} title="Reset view"><RotateCcw size={17}/><span>Reset view</span></button><span className="tool-divider"/><button aria-label={playing?"Pause animation":"Resume animation"} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button aria-label="Zoom in" onClick={()=>setZoom(z=>z+1)}><ZoomIn size={17}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>z-1)}><ZoomOut size={17}/></button><button aria-label={full?"Exit fullscreen":"Enter fullscreen"} onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen();}catch{setInfo(true);}}}>{full?<Minimize size={17}/>:<Maximize size={17}/>}</button></div>
 <div className="scene-hint"><Move size={13}/><span>Drag to orbit</span><span>·</span><span>Scroll to zoom</span></div>
 <button className={"control-layer "+(layer?"selected":"")} onClick={()=>{setAI(true);setPhase(2);setLayer(!layer);setSelected(null);}}><Cpu size={19}/><span><b>AI control layer</b><small>See the connections</small></span><ArrowUpRight size={17}/></button>
 <section className="journey" aria-label="The malting journey"><div className="journey-heading"><span>FOLLOW THE GRAIN</span><span className="legend"><i className="gold"/> Grain <i className="cyan"/> Data <i className="orange"/> Energy</span></div><div className="stage-buttons">{stages.map((s,i)=><button key={s.short} className={selected===i?"stage-button selected":"stage-button"} onClick={()=>choose(i)} aria-pressed={selected===i}><span className="stage-number">0{i+1}</span><span className="stage-label">{s.short}<small>{s.subtitle}</small></span>{i<5&&<ArrowRight className="stage-arrow" size={15}/>}</button>)}</div></section>
 <footer className="footer"><span>INSPIRED BY SOUFFLET & MALT <i/> CONCEPTUAL VISUALIZATION</span><div className="evolution" aria-label="Transformation timeline"><span className="evolution-label">THE EVOLUTION</span>{["Conventional","Connected","AI-enabled"].map((p,i)=><button key={p} className={phase===i?"active":""} aria-pressed={phase===i} onClick={()=>changePhase(i)}><i/>{p}{i<2&&<span className="evolution-line"/>}</button>)}</div></footer>
 <div className="closing-line">From grain to malt, the future of production is connected, predictive and increasingly autonomous.</div>
 </main>;
}
